/**
 * API Configuration
 */
export const API_BASE_URL = import.meta.env.VITE_BACKEND_URL 

export const API_ENDPOINTS = {
  AUTH: {
    MASTER_LOGIN: `${API_BASE_URL}/api/auth/master/login`,
    MASTER_FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/master/forgot-password`,
    MASTER_RESET_PASSWORD: `${API_BASE_URL}/api/auth/master/reset-password`,
    SELLER_LOGIN: `${API_BASE_URL}/api/auth/seller/login`,
    SELLER_FORGOT_PASSWORD: `${API_BASE_URL}/api/auth/seller/forgot-password`,
    SELLER_RESET_PASSWORD: `${API_BASE_URL}/api/auth/seller/reset-password`,
    OUTLET_MAN_LOGIN: `${API_BASE_URL}/api/auth/outlet_man/login`,
    VERIFY_OTP: `${API_BASE_URL}/api/auth/verify-otp`,
    REGISTER: `${API_BASE_URL}/api/auth/register`,
    REFRESH: `${API_BASE_URL}/api/auth/refresh`,
    ME: `${API_BASE_URL}/api/auth/me`,
    USER_SEND_OTP: `${API_BASE_URL}/api/auth/user/send-otp`,
    USER_VERIFY_OTP: `${API_BASE_URL}/api/auth/user/verify-otp`,
    USER_REGISTER: `${API_BASE_URL}/api/auth/user/register`,
    USER_PROFILE: `${API_BASE_URL}/api/auth/user/profile`
  },
  API: {
    REGISTER_MASTER: `${API_BASE_URL}/api/register_master`,
    REGISTER_SELLER: `${API_BASE_URL}/api/register_seller`,
    REGISTER_OUTLET_MAN: `${API_BASE_URL}/api/register_outlet_man`,
    GET_SELLERS: `${API_BASE_URL}/api/sellers`,
    GET_OUTLET_MEN: `${API_BASE_URL}/api/outlet_men`,
    GET_MASTERS: `${API_BASE_URL}/api/masters`,
    GET_BLACKLISTED_SELLERS: `${API_BASE_URL}/api/sellers/blacklisted`,
    GET_BLACKLISTED_OUTLET_MEN: `${API_BASE_URL}/api/outlet_men/blacklisted`,
    UPDATE_SELLER: (sellerId) => `${API_BASE_URL}/api/sellers/${sellerId}`,
    UPDATE_OUTLET_MAN: (outletManId) => `${API_BASE_URL}/api/outlet_men/${outletManId}`,
    BLACKLIST_SELLER: (sellerId) => `${API_BASE_URL}/api/sellers/${sellerId}/blacklist`,
    BLACKLIST_OUTLET_MAN: (outletManId) => `${API_BASE_URL}/api/outlet_men/${outletManId}/blacklist`,
    UNBLACKLIST_OUTLET_MAN: (outletManId) => `${API_BASE_URL}/api/outlet_men/${outletManId}/blacklist`,
    PRODUCTS: `${API_BASE_URL}/api/products`,
    SELLER_PRODUCTS: `${API_BASE_URL}/api/seller/products`,
    SELLER_PRODUCT: (productId) => `${API_BASE_URL}/api/seller/products/${productId}`,
    CATEGORIES: `${API_BASE_URL}/api/categories`,
    PRODUCT_RATINGS: (productId) => `${API_BASE_URL}/api/products/${productId}/ratings`,
    PRODUCT_RATING_STATS: (productId) => `${API_BASE_URL}/api/products/${productId}/ratings/stats`,
    MY_RATING: (productId) => `${API_BASE_URL}/api/products/${productId}/ratings/me`,
    RATING_CATEGORY: (category) => `${API_BASE_URL}/api/ratings/category/${category}`,
    DELETE_RATING: (ratingId) => `${API_BASE_URL}/api/ratings/${ratingId}`,
    WISHLIST: `${API_BASE_URL}/api/wishlist`,
    WISHLIST_ITEM: (productId) => `${API_BASE_URL}/api/wishlist/${productId}`,
    ORDERS: `${API_BASE_URL}/api/orders`,
    ORDER: (orderId) => `${API_BASE_URL}/api/orders/${orderId}`,
    ORDER_ACCEPT: (orderId) => `${API_BASE_URL}/api/orders/${orderId}/accept`,
    ORDER_REJECT: (orderId) => `${API_BASE_URL}/api/orders/${orderId}/reject`,
    ORDER_SCAN: `${API_BASE_URL}/api/orders/scan`,
    ORDER_STATUS: (orderId) => `${API_BASE_URL}/api/orders/${orderId}/status`,
    ORDER_CANCEL: (orderId) => `${API_BASE_URL}/api/orders/${orderId}/cancel`,
    ORDER_CANCEL_MASTER: (orderId) => `${API_BASE_URL}/api/orders/${orderId}/cancel-master`,
    BAG: `${API_BASE_URL}/api/bag`,
    BAG_ITEM: (bagItemId) => `${API_BASE_URL}/api/bag/${bagItemId}`,
    BAG_CLEAR: `${API_BASE_URL}/api/bag/clear`,
    COMMISSION_APPLY_ALL: `${API_BASE_URL}/api/commission/apply-all`,
    COMMISSION_APPLY_CATEGORY: `${API_BASE_URL}/api/commission/apply-category`,
    COMMISSION_APPLY_PRODUCT: `${API_BASE_URL}/api/commission/apply-product`,
    COMMISSION_CATEGORY_RATES: `${API_BASE_URL}/api/commission/category-rates`,
    PENDING_PRODUCTS: `${API_BASE_URL}/api/products/pending`,
    APPROVE_PRODUCT: (productId) => `${API_BASE_URL}/api/products/${productId}/approve`,
    REJECT_PRODUCT: (productId) => `${API_BASE_URL}/api/products/${productId}/reject`,
    ANALYTICS: {
      STATS: `${API_BASE_URL}/api/analytics/stats`,
      USERS: `${API_BASE_URL}/api/analytics/users`,
      SALES_BY_CATEGORY: `${API_BASE_URL}/api/analytics/sales-by-category`,
      SALES_TREND: `${API_BASE_URL}/api/analytics/sales-trend`,
      ORDERS_BY_STATUS: `${API_BASE_URL}/api/analytics/orders-by-status`,
      REVENUE_VS_COMMISSIONS: `${API_BASE_URL}/api/analytics/revenue-vs-commissions`,
      CUSTOMER_GROWTH: `${API_BASE_URL}/api/analytics/customer-growth`,
      RETURNING_VS_NEW: `${API_BASE_URL}/api/analytics/returning-vs-new`,
      STOCK_LEVELS: `${API_BASE_URL}/api/analytics/stock-levels`,
      TOP_PRODUCTS: `${API_BASE_URL}/api/analytics/top-products`,
      SALES_BY_SELLER: `${API_BASE_URL}/api/analytics/sales-by-seller`,
      ACTIVE_COUNTS: `${API_BASE_URL}/api/analytics/active-counts`
    }
  }
}

