/**
 * Pages barrel export
 */
export { default as Home } from './user/Home'
export { default as PublicProductDetail } from './user/PublicProductDetail'
export { default as PhoneNumberEntry } from './user/PhoneNumberEntry'
export { default as OTPVerification } from './user/OTPVerification'
export { default as UserRegistration } from './user/UserRegistration'
export { default as UserProfile } from './user/UserProfile'
export { default as UserOrders } from './user/UserOrders'
export { default as BuyNow } from './user/BuyNow'
export { default as Bag } from './user/Bag'
export { default as Seller } from './seller/Seller'
export { default as SellerMyProducts } from './seller/MyProducts'
export { default as SellerProductDetail } from './seller/ProductDetail'
export { default as SellerAddProduct } from './seller/AddProduct'
export { default as SellerEditProduct } from './seller/EditProduct'
export { default as Master } from './master/Master'
export { default as MasterProductDetail } from './master/ProductDetail'
export { default as SellerLogin } from './seller/Login'
export { default as MasterLogin } from './master/Login'
export { default as OutletLogin } from './outlet/Login'
export { default as Outlet } from './outlet/Outlet'
export { default as NotFound } from './NotFound'
export { default as CategoryProducts } from './user/CategoryProducts'
export { default as AllProducts } from './user/AllProducts'
export { default as Services } from './user/Services'
export { default as Wishlist } from './user/Wishlist'
export { default as SearchResults } from './user/SearchResults'

